---
- hosts: servers
  become: true
  tasks:
    - name: Update package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist

    - name: Remove unused dependencies
      ansible.builtin.apt:
        autoremove: yes

    - name: Clean up package cache
      ansible.builtin.apt:
        autoclean: yes